---
title: "Problem 2"
author: "Ye Yuan"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)
```

```{r}
NOAA <- ny_noaa |>
  janitor::clean_names() |>
  mutate(tmax = as.numeric(tmax),
         tmin = as.numeric(tmin),
         prcp = prcp / 10,
         tmax = tmax / 10,
         tmin = tmin / 10,
         year = lubridate::year(date),
         month = lubridate::month(date))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
NOAA |>
  filter(!is.na(prcp), year == 1998) |>
  group_by(month) |>
  plot_ly(x = ~month, y = ~prcp, color = ~month,
          type = "bar", colors = "viridis") |>
  layout(
    title = "Preceptation by Month in 1998",
    xaxis = list(title = "Month"),
    yaxis = list(title = "Preceptation (mm)")
  )
```



### Chart B

```{r}
NOAA |>
  filter(!is.na(snow), year == 1998) |>
  group_by(month) |>
  plot_ly(x = ~month, y = ~snow,
          type = "scatter", mode = "markers", symbol = c("o"),
          color = I("black"), marker = list(size = 2)) |>
  layout(
    title = "Snowfall Distribution by Month in 1998",
    xaxis = list(title = "Month"),
    yaxis = list(title = "Snowfall")
  )

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart C

```{r}
NOAA |>
  filter(!is.na(tmax), year == 1998) |>
  group_by(month) |>
  plot_ly(x = ~month, y = ~tmax, color = ~month,
          type = "box", colors = "viridis") |>
  layout(
    title = "Max Temp Distribution by Month in 1998",
    xaxis = list(title = "Month"),
    yaxis = list(title = "Temperature")
  )
```

### Chart D
```{r}
NOAA |>
  filter(!is.na(tmin), year == 1998) |>
  group_by(month) |>
  plot_ly(x = ~month, y = ~tmin, color = ~month,
          type = "box", colors = "viridis") |>
  layout(
    title = "Min Temp Distribution by Month in 1998",
    xaxis = list(title = "Month"),
    yaxis = list(title = "Temperature")
  )
```